# -*- coding: utf-8 -*-
"""Buffer_data_plots.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JU1eWICvgdH5VU0DZ1bOE55czu83u6j_
"""

import matplotlib.pyplot as plt
import json
import seaborn as sns
import pandas as pd
# plt.rcParams["figure.figsize"] = (15,3)
buffer_data = json.load(open('v1diffbuffer.json', 'r'))
df = pd.DataFrame(buffer_data)

fig, ax = plt.subplots(figsize=(10, 8))
sns.lineplot(x="frameID", y="tracking_metric", data=df, ax=ax)
# sns.set(font_scale=1)
# sns.set(rc={'figure.figsize':(1)})
plt.show()

fig, ax = plt.subplots(figsize=(10, 8))
sns.lineplot(x="frameID", y="stepSize", data=df, ax=ax)
# sns.set(font_scale=2.5)
# sns.set(rc={'figure.figsize':(15,15)})
plt.show()

fig, ax = plt.subplots(figsize=(10, 8))
sns.lineplot(x="frameID", y="bufferLength", data=df, ax=ax)
# sns.set(font_scale=2.5)
# sns.set(rc={'figure.figsize':(30,15)})
plt.show()

fig, ax = plt.subplots(figsize=(10, 8))
sns.lineplot(x="frameID", y="velocity", data=df, ax=ax)
# sns.set(font_scale=2.5)
# sns.set(rc={'figure.figsize':(30,15)})
plt.show()



import json
import pandas as pd

buffer_data = json.load(open('v1diffbuffer.json', 'r'))
df = pd.DataFrame(buffer_data)

df.to_csv("v1diffbuffer.json.csv")
