# -*- coding: utf-8 -*-
"""CDF & PDF plots_ROS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18D7Et8sjfKSFcPpF9vh96dXYm5gdm1zo
"""

# Commented out IPython magic to ensure Python compatibility.
import csv
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
# %matplotlib inline

"""MH01 EuRoC using ROSbag"""

from pandas import *
 
data = read_csv("Time_Process_ROS.csv")
frame = data['Frame'].tolist()
process_time = data['Processing Time'].tolist()
frame_count = len(frame)
print('Number of frames processed:', frame_count)
print('Frame ID:', frame)
print('Processing time per frame:', process_time)

count, bins_count = np.histogram(process_time, bins=10)
# print(count)
# print(bins_count)
pdf = count / sum(count)
cdf = np.cumsum(pdf)

plt.hist(process_time, color="brown", edgecolor="white", bins=10)
plt.title("Sensor: Monocular ROS   Sequence: Euroc MH01")
plt.xlabel("Processing Time (Seconds)")
plt.ylabel("Frames")
plt.show()

plt.plot(bins_count[1:], pdf, color="red", label="PDF")
plt.plot(bins_count[1:], cdf, label="CDF")
plt.title("Monocular ROS on Euroc MH01")
plt.xlabel("Processing Time (Seconds)")
plt.ylabel("Probability Density")
plt.legend()

"""MH01 EuRoC ROSbag from node (flexible system)"""

from pandas import *
 
data1 = read_csv("Time_ROS_MH01_Node.csv")
frame1 = data1['Frame'].tolist()
process_time1 = data1['Processing Time'].tolist()
frame_count = len(frame1)
print('Number of frames processed:', frame_count)
print('Frame ID:', frame1)
print('Processing time per frame:', process_time1)

count, bins_count = np.histogram(process_time1, bins=10)
# print(count)
# print(bins_count)
pdf1 = count / sum(count)
cdf1 = np.cumsum(pdf1)

plt.hist(process_time1, color="brown", edgecolor="white", bins=10)
plt.title("Sensor: Monocular ROS   Sequence: Euroc MH01")
plt.xlabel("Processing Time (Seconds)")
plt.ylabel("Frames")
plt.show()

plt.plot(bins_count[1:], pdf1, color="red", label="PDF")
plt.plot(bins_count[1:], cdf1, label="CDF")
plt.title("Monocular ROS on Euroc MH01")
plt.xlabel("Processing Time (Seconds)")
plt.ylabel("Probability Density")
plt.legend()

"""MH01 EuRoC ROS with flexibility and restricted CPU speed

"""

from pandas import *
 
data2 = read_csv("Time_ROS_MH01_Node restricted.csv")
frame2 = data2['Frame'].tolist()
process_time2 = data2['Processing Time'].tolist()
frame_count = len(frame2)
print('Number of frames processed:', frame_count)
print('Frame ID:', frame2)
print('Processing time per frame:', process_time2)

count, bins_count = np.histogram(process_time, bins=10)
# print(count)
# print(bins_count)
pdf2 = count / sum(count)
cdf2 = np.cumsum(pdf2)

plt.hist(process_time2, color="brown", edgecolor="white", bins=10)
plt.title("Sensor: Monocular ROS   Sequence: Euroc MH01")
plt.xlabel("Processing Time (Seconds)")
plt.ylabel("Frames")
plt.show()

plt.plot(bins_count[1:], pdf2, color="red", label="PDF")
plt.plot(bins_count[1:], cdf2, label="CDF")
plt.title("Monocular ROS on Euroc MH01")
plt.xlabel("Processing Time (Seconds)")
plt.ylabel("Probability Density")
plt.legend()

"""MH04 EuRoC using ROSbag"""

from pandas import *
 
data2 = read_csv("Time_ROS_MH04_Rosbag.csv")
frame2 = data2['Frame'].tolist()
process_time2 = data2['Processing Time'].tolist()
frame_count = len(frame2)
print('Number of frames processed:', frame_count)
print('Frame ID:', frame2)
print('Processing time per frame:', process_time2)

count, bins_count = np.histogram(process_time, bins=10)
# print(count)
# print(bins_count)
pdf2 = count / sum(count)
cdf2 = np.cumsum(pdf2)

plt.hist(process_time2, color="brown", edgecolor="white", bins=10)
plt.title("Sensor: Monocular ROS   Sequence: Euroc MH01")
plt.xlabel("Processing Time (Seconds)")
plt.ylabel("Frames")
plt.show()

plt.plot(bins_count[1:], pdf2, color="red", label="PDF")
plt.plot(bins_count[1:], cdf2, label="CDF")
plt.title("Monocular ROS on Euroc MH01")
plt.xlabel("Processing Time (Seconds)")
plt.ylabel("Probability Density")
plt.legend()

"""MH04 EuRoC ROSbag from node (flexible system)"""

from pandas import *
 
data2 = read_csv("Time_ROS_MH04_Node.csv")
frame2 = data2['Frame'].tolist()
process_time2 = data2['Processing Time'].tolist()
frame_count = len(frame2)
print('Number of frames processed:', frame_count)
print('Frame ID:', frame2)
print('Processing time per frame:', process_time2)

count, bins_count = np.histogram(process_time, bins=10)
# print(count)
# print(bins_count)
pdf2 = count / sum(count)
cdf2 = np.cumsum(pdf2)

plt.hist(process_time2, color="brown", edgecolor="white", bins=10)
plt.title("Sensor: Monocular ROS   Sequence: Euroc MH01")
plt.xlabel("Processing Time (Seconds)")
plt.ylabel("Frames")
plt.show()

plt.plot(bins_count[1:], pdf2, color="red", label="PDF")
plt.plot(bins_count[1:], cdf2, label="CDF")
plt.title("Monocular ROS on Euroc MH01")
plt.xlabel("Processing Time (Seconds)")
plt.ylabel("Probability Density")
plt.legend()

"""MH04 EuRoC ROS with flexibility and restricted CPU speed

"""

from pandas import *
 
data2 = read_csv("Time_ROS_MH04_Node restricted.csv")
frame2 = data2['Frame'].tolist()
process_time2 = data2['Processing Time'].tolist()
frame_count = len(frame2)
print('Number of frames processed:', frame_count)
print('Frame ID:', frame2)
print('Processing time per frame:', process_time2)

count, bins_count = np.histogram(process_time, bins=10)
# print(count)
# print(bins_count)
pdf2 = count / sum(count)
cdf2 = np.cumsum(pdf2)

plt.hist(process_time2, color="brown", edgecolor="white", bins=10)
plt.title("Sensor: Monocular ROS   Sequence: Euroc MH01")
plt.xlabel("Processing Time (Seconds)")
plt.ylabel("Frames")
plt.show()

plt.plot(bins_count[1:], pdf2, color="red", label="PDF")
plt.plot(bins_count[1:], cdf2, label="CDF")
plt.title("Monocular ROS on Euroc MH01")
plt.xlabel("Processing Time (Seconds)")
plt.ylabel("Probability Density")
plt.legend()
