# -*- coding: utf-8 -*-
"""CDF and PDF analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1msoL0S2nUof-k7yn-zJHQSSVj-p5cRfq

### Monocular Euroc MH01
"""

# Commented out IPython magic to ensure Python compatibility.
import csv
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
# %matplotlib inline

# with open('Time_mono_euroc_MH01.csv', 'r') as file:
#     reader = csv.reader(file)
#     for row in reader:
#         print(row)

from pandas import *
 
data = read_csv("Time_mono_euroc_MH01.csv")
frame = data['Frame'].tolist()
process_time = data['Processing time'].tolist()

print('Frame ID:', frame)
print('Processing time per frame:', process_time)

count, bins_count = np.histogram(process_time, bins=10)
# print(count)
# print(bins_count)
pdf = count / sum(count)
cdf = np.cumsum(pdf)

plt.hist(process_time, color="brown", edgecolor="white", bins=10)
plt.title("Sensor: Monocular   Sequence: Euroc MH01")
plt.xlabel("Processing Time (Seconds)")
plt.ylabel("Frames")
plt.show()

plt.plot(bins_count[1:], pdf, color="red", label="PDF")
plt.plot(bins_count[1:], cdf, label="CDF")
plt.title("Monocular on Euroc MH01")
plt.legend()

"""### Stereo Euroc MH01"""

from pandas import *
 
data = read_csv("Time_stereo_euroc_MH01.csv")
frame = data['Frame'].tolist()
process_time = data['Processing time'].tolist()

print('Frame ID:', frame) #column name to print data from
print('Processing time per frame:', process_time)

count, bins_count = np.histogram(process_time, bins=10)
# print(count)
# print(bins_count)
pdf = count / sum(count)
cdf = np.cumsum(pdf)

plt.hist(process_time, color="brown", edgecolor="white", bins=10)
plt.title("Sensor: Stereo   Sequence: Euroc MH01")
plt.xlabel("Processing Time (Seconds)")
plt.ylabel("Frames")
plt.show()

plt.plot(bins_count[1:], pdf, color="red", label="PDF")
plt.plot(bins_count[1:], cdf, label="CDF")
plt.title("Stereo on Euroc MH01")
plt.legend()

"""### Monocular Euroc MH04"""

from pandas import *
 
data = read_csv("Time_mono_euroc_MH04.csv")
frame = data['Frame'].tolist()
process_time = data['Processing time'].tolist()

print('Frame ID:', frame)
print('Processing time per frame:', process_time)

count, bins_count = np.histogram(process_time, bins=10)
pdf = count / sum(count)
cdf = np.cumsum(pdf)

plt.hist(process_time, color="brown", edgecolor="white", bins=10)
plt.title("Sensor: Monocular   Sequence: Euroc MH04")
plt.xlabel("Processing Time (Seconds)")
plt.ylabel("Frames")
plt.show()

plt.plot(bins_count[1:], pdf, color="red", label="PDF")
plt.plot(bins_count[1:], cdf, label="CDF")
plt.title("Monocular on Euroc MH04")
plt.legend()

"""### Stereo Euroc MH04"""

from pandas import *
 
data = read_csv("Time_stereo_euroc_MH04.csv")
frame = data['Frame'].tolist()
process_time = data['Processing time'].tolist()

print('Frame ID:', frame)
print('Processing time per frame:', process_time)

count, bins_count = np.histogram(process_time, bins=10)
pdf = count / sum(count)
cdf = np.cumsum(pdf)

plt.hist(process_time, color="brown", edgecolor="white", bins=10)
plt.title("Sensor: Stereo   Sequence: Euroc MH04")
plt.xlabel("Processing Time (Seconds)")
plt.ylabel("Frames")
plt.show()

plt.plot(bins_count[1:], pdf, color="red", label="PDF")
plt.plot(bins_count[1:], cdf, label="CDF")
plt.title("Stereo on Euroc MH04")
plt.legend()

"""### Monocular TUM room 4"""

from pandas import *

data = read_csv("Time_mono_Tum_room4.csv")
frame = data['Frame'].tolist()
process_time = data['Processing time'].tolist()

print('Frame ID:', frame)
print('Processing time per frame:', process_time)

count, bins_count = np.histogram(process_time, bins=10)
pdf = count / sum(count)
cdf = np.cumsum(pdf)

plt.hist(process_time, color="brown", edgecolor="white", bins=10)
plt.title("Sensor: Monocular   Sequence: TUM room 4")
plt.xlabel("Processing Time (Seconds)")
plt.ylabel("Frames")
plt.show()

plt.plot(bins_count[1:], pdf, color="red", label="PDF")
plt.plot(bins_count[1:], cdf, label="CDF")
plt.title("Monocular on TUM room 4")
plt.legend()

"""### Stereo TUM room 4"""

from pandas import *
 
data = read_csv("Time_stereo_Tum_room4.csv")
frame = data['Frame'].tolist()
process_time = data['Processing time'].tolist()

print('Frame ID:', frame)
print('Processing time per frame:', process_time)

count, bins_count = np.histogram(process_time, bins=10)
pdf = count / sum(count)
cdf = np.cumsum(pdf)

plt.hist(process_time, color="brown", edgecolor="white", bins=10)
plt.title("Sensor: Stereo   Sequence: TUM room 4")
plt.xlabel("Processing Time (Seconds)")
plt.ylabel("Frames")
plt.show()

plt.plot(bins_count[1:], pdf, color="red", label="PDF")
plt.plot(bins_count[1:], cdf, label="CDF")
plt.title("Stereo on TUM room 4")
plt.legend()